### ISSUE TITLE
conf.py can be confused with library code

### ISSUE THREAD

**Issue by deshipu** [adafruit/cookiecutter-adafruit-circuitpython#1]
I wonder if it's a good idea to have the `conf.py` and all the documentation at the top level of the repositories, and not in a `docs` directory like all the other projects. I think it's pretty easy to get confused and copy the conf.py file to the board together with the other library files, and then panic when another library has the same file and there is a conflict. As far as I understand how Sphinx works, it's possible to use relative paths with ".." in them in its configuration, so the `README` file could still reside at the top level, even if `conf.py` was moved to `docs`.

**Comment by tannewt** [comment]
Could you give it a try? If it works moving it to `docs` that sounds good to me. My goal was just to be able to pull documentation from the README and the source files.

**Comment by tannewt** [comment]
@deshipu this is still a good idea right? We should do it sooner rather than later if we want to. I think @willingc also suggested this.

**Comment by dhalbert** [comment]
Right now the internal frozen modules implementation discards `conf.py` and `setup.py` at the top level. It does not expect a `docs` directory that should be ignored. If we add that, code should change here: https://github.com/adafruit/circuitpython/blob/master/tools/preprocess_frozen_modules.py

**Comment by dhalbert** [comment]
Fixed by #15.
