### ISSUE TITLE
"CircuitPython" not added consistently

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/cookiecutter-adafruit-circuitpython#100]
I'm publishing my first library and first, let me say this is GREAT! Thank you!

I wanted to have my library named CircuitPython_Magic and I did not want to supply a prefix.

If you supply library_name CircuitPython_MAGIC:

1. __repo__ = "https://github.com/askpatrickw/CircuitPython_CircuitPython_Magic.git"
2. Folder created is CircuitPython_MAGIC.
3. library .py file name is circuitpython_magic.py

If you supply just Magic:

1. __repo__ = "https://github.com/askpatrickw/CircuitPython_Magic.git"
2. Folder created is Magic.
3. library .py file name is magic.py

I suggest ading a question Y\N to add `CircuitPython` between the prefix and the library name and if Yes, to have it be added to the  __repo__, folder name created and library name. OR just always do this and don't prompt.

From the names of libraries in the community bundle today, I don't think I would ever find them if it wasn't for bundle. Adding CircuitPython would make them more discoverable.

As I went through the files, I found more inconsistently named items:

- [ ] folder created on disk
- [ ] library .py filename
- [ ] __repo__ in .py
- [ ] in Readme.rst
  - [ ] Documentation and Build status urls
  - [ ] PyPi url 
  - [ ] Pip install steps
- [ ] PyPI section has adafruit in all names

**Comment by kattni** [comment]
@askpatrickw This is all good. We can pretty much do whatever we want with this, but the thing we have to bear in mind is, the guide will need to be updated to go with it. Essentially, as long as we document it, it's fine. The guide is pretty explicit with each of the prompts, so we need to make sure the update doesn't lag too far behind or folks will be confused and have no documentation to alleviate that.

All of that said, a majority of the libraries being created out of this cookiecutter are Adafruit libraries. So we want to make sure we're not creating confusion or a lot more work for folks creating Adafruit libraries.

As for your specific question, I'm ok with adding a question about having the CircuitPython prefix, as long as it defaults to including the prefix.

As for the list you provided, if it's possible to make it so the community bundle version has some seriously different options, I think it would be worth it. By different options, I mean things like not including the PyPI info in the README, not including setup.py (or any of the PyPI related info as if folks are deploying to PyPI they need to handle that on their own), and having the README look different overall I guess as the links to docs and so on wouldn't apply, etc.

If possible, please look into whether this is feasible. I don't know enough about cookiecutter to help here. 

If it's not feasible, then please do your best to make it so we're not adding a huge list of prompts, but still creating a usable Community bundle option.

**Comment by askpatrickw** [comment]
I'm going to address these things in the Conversation on the PR #84
