### ISSUE TITLE
How should Copyright be applied to files AND Should anything be default no in Community?

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/cookiecutter-adafruit-circuitpython#103]
This conversation is only about the files within the template folder which in the master branch is called `{{ cookiecutter.library_name }}` today.

These are the ways copyright is added today:

## Template Author & Library Author
Some files have a copyright line crediting Scott and then an added line for the author is appended.

```
# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
# SPDX-FileCopyrightText: Copyright (c) {% now 'utc', '%Y' %} {{ cookiecutter.author }}{% if cookiecutter.company %} for {{ cookiecutter.company }}{% endif %}
#
# SPDX-License-Identifier: MIT
```
- library_name.py
- setup.py
- requirements.txt

## Author Only
The author is added when the template is processed

- LICENSE

## Coraline and Kattni

- Code_of_Conduct.md

## Diego only

- pyproject.toml
- pre-commit-config.yaml

## Scott only

- readme.rst (I believe via readme.rst.license)
- .readthedocs.yml
- .pylintrc
- .gitignore
- .github/workflow/build.yml
- .github/workflow/release.yml
- examples/library_name_simpletest.py
- Everything in docs except the favicon which is Phillip

I thought this was messier than it actually is, but here's my proposal and question:

1. Add the Author the examples file, and Readme file.
3. Add a sphinx_docs to the cookiecutter which defaults to Yes for Adafruit and No for Community and if NO, excludes the Docs folder and readthedocs.yml

I could be talked out of  2. Just my opinion. I don't see everyone wanting the docs, they will just update the readme I'm sure and that's it.

**Comment by askpatrickw** [comment]
@kattni  Let me know your thoughts on this.

**Comment by tannewt** [comment]
We should add the library author to any file we expect them to edit. I know a number of the docs have todos that will break the build for example. Thanks!

**Comment by askpatrickw** [comment]
Thanks @tannewt !

@kattni Here's my updated proposal:

1. Add the Author the examples file, Readme and Everything in docs except the favicon which is Phillip.
2. Add a sphinx_docs to the cookiecutter which defaults to Yes for Adafruit and No for Community and if NO, excludes the Docs folder and readthedocs.yml

I have #2 working locally using a post_gen hook to remove the docs folder and it works. The empty folder name method would require applying that if logic to every file in the docs folder and that looks horrible. But it could also be done that way too.

**Comment by kattni** [comment]
@askpatrickw I suppose if someone really wants to host their own docs on RTD, they can figure out creating the appropriate files. Seems like most folks are likely to use the README as documentation. I think excluding those files is fine. And I agree the author should be added to any files we expect them to edit.
