### ISSUE TITLE
(Nearly) replacing setup.py with pyproject.toml and setup.cfg

### ISSUE THREAD

**Issue by dhalbert** [adafruit/cookiecutter-adafruit-circuitpython#119]
PEP517 and PEP518 create a new mechanism for installation that does not need a setup.py:
https://snarky.ca/what-the-heck-is-pyproject-toml/

(but see minor caveat at the end about editable installs)

Related to #118.

**Comment by tannewt** [comment]
FWIW, I've been liking `flit` with pyproject.toml. https://flit.readthedocs.io/en/latest/

**Comment by tekktrik** [comment]
Resolved by #194 and #195
