### ISSUE TITLE
Remove Adafruit Bus Device library dependency question & comments?

### ISSUE THREAD

**Issue by durapensa** [adafruit/cookiecutter-adafruit-circuitpython#122]
Adafruit Bus Device library `adafruit_bus_device` is now included with CP.

**Comment by dhalbert** [comment]
It is a native module on most but not all boards. On the smallest boards (mostly SAMD21), it does not fit.

Also, Blinka does not implement it in `adafruit-blinka`, so it is still needed when libraries are used under Blinka.

**Comment by durapensa** [comment]
Okay, I thought that might be the case. Is it possible to make the question clearer?

I left the answer blank, but cookiecutter still added the dependency to module.py "Software and Dependencies" section.

BTW I'm using cookiecutter & nbdev together, working out conflicts, etc. Some notes here https://gist.github.com/durapensa/03fafa125476b1b70b394d17b036e2c0

**Comment by askpatrickw** [comment]
NOTE: It is hard to make the questions clearer. Cookiecutter doesn't support (last I checked) a description to go with the prompts. I wish it did.

**Comment by tekktrik** [comment]
I think it's safe to close this as "won't fix" given the discussion.  It may be worth reopening if question descriptions are ever possible.  I checked and `requirements.txt` only adds the selected library(s), though this issue could be updated to suggest that the note in the module docstring regarding BusDevice and Register only show up based on the selection (though there are already other TODOs across the generated repository).
