### ISSUE TITLE
 Installing from Circup

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/cookiecutter-adafruit-circuitpython#131]
Please add an *Installing from Circup* section in README.rst similar to the *Installing from PyPI* section.

An example might be:

```
Installing to a connected CircuitPython Device with Circup
==========================================================

Make sure that you have ``circup`` installed in your ``pip`` environment.
Install it with the following command if necessary:

.. code-block:: shell

    pip3 install circup

With ``circup`` installed and your CircuitPython device connected use the
following command to install:

.. code-block:: shell

    circup install adafruit-circuitpython-LIBRARY_NAME

Or the following command to update an existing version:

.. code-block:: shell

    circup update
```

**Comment by askpatrickw** [comment]
Sorry about this... I don't know it happened. Despite VSCode and my cli saying I was on a branch in my clone, I committed to Master.

![image](https://user-images.githubusercontent.com/4002194/120941184-27ebd500-c6d6-11eb-91a5-78e418a78ddc.png)

I think the changes was safe so I don't think we need to back it out.

**Comment by lesamouraipourpre** [comment]
It looks like it was only a change to README.rst, so there shouldn't be an issue.

If you have access to the repository settings, there is a way to protect the main/master branch so it it can't be pushed to. 
I think its `Settings` > `Branches` > `Branch protection rules - Add Rule` > Select `Require pull request reviews before merging `
