### ISSUE TITLE
Community library - Code of Conduct

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/cookiecutter-adafruit-circuitpython#141]
When generating a community library with ~circup~ `cookiecutter` it uses the standard `CODE_OF_CONDUCT.md` that it uses for Adafruit libraries.

Example: https://github.com/lesamouraipourpre/Community_CircuitPython_TCA9555/blob/HEAD/CODE_OF_CONDUCT.md

There are parts in this which seem to be Adafruit specific in particular the *Moderation* and *Scope* sections. While I would obviously respect any reports received through these channels, I feel this puts undue responsibility on the Adafruit Team/Adafruit Discord Team.

Should this use a less branded, library specific Code of Conduct, possibly a 'CircuitPython Community Code of Conduct' (CCCoC) and should ~circup~ `cookiecutter` be amended to provide this version?

If we were to go for a generic CCCoC, what should it say in these sections?

**Comment by jposada202020** [comment]
@kattni.. Thanks :)

**Comment by askpatrickw** [comment]
It will be a challenge to have some other path for reporting until a day when there is a more formal organization around CP. I'm sure that's the dream... But until then, if Adafruit would like to have more outside help (and maybe they're fine with things as-is),  I wonder if the PSF could be useful in this regard? Maybe they could be a place where concerns are sent. But then where and to who would they go next?

**Comment by kattni** [comment]
Hey folks. I definitely agree there should be a more general CoC for community libraries. Adafruit does not need outside assistance for supporting our scope, but while we host the Community Bundle, supporting any community surrounding individual libraries does not fall within that scope.

Ostensibly, support and moderation issues for a community library are the responsibility of the maintainer. If you as a maintainer or folks contributing to your project are being harassed on your own GitHub repo, it is up to you to handle it accordingly. 

I would suggest changing the wording in the Adafruit-specific sections to refer to "maintainer" and "project" for a more generalised approach. I suggest creating an issue for it (or continuing on this issue) - this repo is an acceptable place for it - and having a discussion amongst as many of the Community Bundle contributors as would like to be a part of it, and come up with what you'd like to see for that CoC. I'm happy to help with this.

**Comment by askpatrickw** [comment]
Thanks @kattni, do you want to do a CoC PR to use as a basis for discussion or would like us to do that?

**Comment by kattni** [comment]
@askpatrickw A PR is a great idea as changes can be discussed in-line.

Unrelated - the current CoC never got updated when we updated the overall one. I need to make a PR for that.

Therefore (related) I'll get that PR in and then put in a PR for this once that PR is merged.

I'll try to get to that today. If not, it'll be tomorrow.

**Comment by tannewt** [comment]
I think the Community CoC could refer to a discord role or we could make a community group email. I think we've only ever had one or two emails to support@ since we've started. Most moderation activity happens between Discord mods.

**Comment by kattni** [comment]
I think the idea is to move away from the expectation that Adafruit is providing support for community libraries which are maintained by the individual submitting it.

I'm working on submitting a PR where we can discuss it and submit suggestions etc.

**Comment by kattni** [comment]
I created a PR as a starting point. I made a few minor changes to begin. None of them need to stay in - I simply wanted to create a place to start.
