### ISSUE TITLE
move actions to use a "composite action" to ease updating actions across all libs

### ISSUE THREAD

**Issue by jepler** [adafruit/cookiecutter-adafruit-circuitpython#150]
For an unrelated thing (arduino ci) I was prototyping the use of a "composite action".  Composite actions can have shell steps and steps that call out to other actions. By making the cookie-cut version of the actions file refer to (an as yet to be created) composite action, we can update all actions simultaneously across all cookie-cut repos. (by using an evergreen `@main` instead of a pinned `@v1`, all workflows would automatically get the newest version of the composite action)

Example composite action for arduino-ci: https://github.com/jepler/actions-arduino-ci/blob/main/action.yml

Example use of it: https://github.com/jepler/Adafruit_SI1145_Library/blob/21eb009648326cdf849beab2263254cf4840fe5d/.github/workflows/githubci.yml

**Comment by tekktrik** [comment]
Oh this is really interesting, I want to look into this!

**Comment by tekktrik** [comment]
Implemented!
