### ISSUE TITLE
Mismatch between folder created and __repo__ in generated source file

### ISSUE THREAD

**Issue by jpconstantineau** [adafruit/cookiecutter-adafruit-circuitpython#154]
I just created a library from the cookiecutter and got the following folder created:

- CircuitPython_pykey

However, in the source file (pykey.py), I got the following repo folder:
-  \_\_repo\_\_ = "https://github.com/jpconstantineau/CircuitPython_Org_pykey.git"

With the "org" bundle getting ready, I am not sure which one is right...

**Comment by FoamyGuy** [comment]
@jpconstantineau which choices did you make for the cookie cutter questions? The first question that it asks is which bundle and there are three choices, Adafruit, Community, CircuitPython Organization.

**Comment by jpconstantineau** [comment]
I am not too sure how I would try it as I just ran it for the first time yesterday and had to figure out all the dependencies for python on an Ubuntu VM first.  Do I simply checkout your specific commit and run cookie cutter to that path? (similar to your example above)

**Comment by FoamyGuy** [comment]
@jpconstantineau you can use a modified version of the cookiecutter command to try out the branch from the PR.
```
cookiecutter gh:foamyguy/cookiecutter-adafruit-circuitpython --checkout repo_url
```
