### ISSUE TITLE
Make the copyright year "evergreen"

### ISSUE THREAD

**Issue by jepler** [adafruit/cookiecutter-adafruit-circuitpython#173]
Based on Discord discussion with @FoamyGuy and @tekktrik we noticed that some recently generated docs on RTD said `Copyright 2019 ...`.

We could use git to find the date the last commit was authored, and use that instead. This command will show the year of the latest commit according to git:
```
git log --format=%ad --date=format:%Y -1
```

`conf.py` would hypothetically use `subprocess` module to run this git command and insert the result in the copyright string, something like
```
copyright_year = subprocess.check_output(['git', 'log', '--format=%ad', '--date=format:%Y', '-1'], stdin=subprocess.DEVNULL, encoding='ascii', errors='ignore').strip()
copyright = f"{copyright_year} Jeff Epler"
```

If we decided to do this it would also be nice to go back and fix existing libs, but because the copyright line will be different in each case (author name and year) it is probably not an automatic adabot patch.

**Comment by tekktrik** [comment]
This is actually something my script tools could handle pretty well, so I think it's worth doing!

**Comment by tekktrik** [comment]
@kattni what are your thoughts?

**Comment by kattni** [comment]
@tekktrik I like it! Let's do it.

**Comment by tekktrik** [comment]
Okay I have a script to make the following changes:

- Import `datetime` at the top
- Use `datetime` to get the current year

```python
# -*- coding: utf-8 -*-

# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
#
# SPDX-License-Identifier: MIT

import os
import sys
import datetime

...

# General information about the project.
project = "Adafruit AHTx0 Library"
current_year = str(datetime.datetime.now().year)
copyright = current_year + " Kattni Rembor"
author = "Kattni Rembor"

...
```

This saves using `git` to check for the last commit, since it should pretty much match the current year.  Plus, documentation built local now has the current year too!

Thoughts on this solution?

**Comment by ladyada** [comment]
yes plz! i have noticed that the cookie spdx has wrong author and date for a bit :)

**Comment by tekktrik** [comment]
@ladyada do you want me to use the datetime solution to force all headers to the year of creation and generating author?

**Comment by ladyada** [comment]
im fine with it yep :)
