### ISSUE TITLE
can we dump black's target python version?

### ISSUE THREAD

**Issue by jepler** [adafruit/cookiecutter-adafruit-circuitpython#174]
I noticed that we currently ask black to work as it would have with python 3.5.  I think our oldest supported is now 3.7 in blinka. Perhaps it could be changed in pyproject.toml.
https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/main/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D%7D/pyproject.toml

**Comment by tekktrik** [comment]
@jepler black should now be fully controlled by the version listed in `.pre-commit-config.yaml`.  Do you still want to dump it in the CI, or close this?

**Comment by jepler** [comment]
yay thanks for noticing that this could be closed up
