### ISSUE TITLE
Update the pre-commit black to 22.3.0 ?

### ISSUE THREAD

**Issue by Neradoc** [adafruit/cookiecutter-adafruit-circuitpython#180]
I created a repo with cookiecutter and the CI failed because of the version issue with black and click.
While we are updating libraries to pass CI, it should be updated here too for new libraries, right ?

https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/12dfdb9e82862e2c95b4cb20b33e6b0627ccdc2f/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D%7D/.pre-commit-config.yaml#L6-L7

**Comment by tekktrik** [comment]
Yeah, it does.  Linking this to https://github.com/adafruit/Adafruit_CircuitPython_TSC2007/pull/2 which I used to propose changes to the cookiecutter before a PR gets made here.  It's pretty recent so it was easier to propose changes to it that can then be ported over to here.
