### ISSUE TITLE
Latest release.yml breaks some libraries

### ISSUE THREAD

**Issue by evaherrada** [adafruit/cookiecutter-adafruit-circuitpython#190]
Been looking into this for the last hour or so and I'm still pretty confused, but I believe I've isolated the issue.

Basically, with the latest release.yml, [these lines](https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/dc7512c60d6056893bba942b1a3d015f9744a754/%7B%7B%20cookiecutter.__dirname%20%7D%7D/.github/workflows/release.yml#L84-L86) cause something weird to happen with the version on some libraries. 
![Screenshot_2022-07-22_15-37-48](https://user-images.githubusercontent.com/33632497/180516598-5c3f84fc-b7ce-4cc7-9ac3-1f161a60c48d.png)

An example of this is MONSTERM4SK

The library initially fails on something unrelated, due to an out of date release.yml
https://github.com/adafruit/Adafruit_CircuitPython_MONSTERM4SK/runs/7473927927?check_suite_focus=true

I copied over the latest release.yml and it then started failing because for some reason the lines I'm referencing were renaming files incorrectly. The release tag for this run was 0.3.7, but as you can see it's putting it as 0.3.8. https://github.com/adafruit/Adafruit_CircuitPython_MONSTERM4SK/runs/7474367164?check_suite_focus=true#step:6:25
![Screenshot_2022-07-22_15-39-54](https://user-images.githubusercontent.com/33632497/180516641-f0804125-edfa-4836-a656-fdac80f27278.png)

I initially thought it could be an issue with `github.event.release.tag_name`, and while I'm not ruling that out, when the command with the double curly braces filled in is printed, it does print the correct version.
![Screenshot_2022-07-22_15-51-45](https://user-images.githubusercontent.com/33632497/180517462-f6cec35b-6c1c-464c-9c89-70309dab45cd.png)

I rolled the version back to the most common version and it passed. https://github.com/adafruit/Adafruit_CircuitPython_MONSTERM4SK/runs/7474386722?check_suite_focus=true#step:6:22
![Screenshot_2022-07-22_15-42-57](https://user-images.githubusercontent.com/33632497/180516671-8c77d5e6-c4f0-4d8c-b879-43e096970961.png)

You can also see this here ([broken with latest version](https://github.com/adafruit/Adafruit_CircuitPython_OV5640/runs/7474256021?check_suite_focus=true) and then [fixed with older version](https://github.com/adafruit/Adafruit_CircuitPython_OV5640/runs/7474504983?check_suite_focus=true))

[The older version I've replaced it with](https://gist.github.com/evaherrada/21d59722c4f605dad0ba3a7709c8f66b) is the one that's used by 263 CircuitPython libraries

**Comment by dhalbert** [comment]
```sh
        for file in $(find -not -path "./.*" -not -path "./docs*" -name "*.py"); do
```
Shouldn't the args be in single-quotes, not double quotes (assuming they are executed in a shell)? Otherwise the wilcarding will happen immediately.

**Comment by evaherrada** [comment]
So I actually did try this locally, and weirdly enough all it seemed to do was change the version in the file, which is what I'm assuming it's supposed to do. Not sure why it seems to be acting so differently on the CI

**Comment by dhalbert** [comment]
The MONSTERM4SK error is because it is running Python 3.6. There's something wrong about the specification of the Python version.

**Comment by evaherrada** [comment]
> The MONSTERM4SK error is because it is running Python 3.6. There's something wrong about the specification of the Python version.

Yeah, this is the original reason I tried to put in the new release.yml. After I put the new release.yml in I no longer ran into the `from __future__ import annotations` issue but started running into the issue I'm describing above

**Comment by evaherrada** [comment]
> Shouldn't the args be in single-quotes, not double quotes (assuming they are executed in a shell)? Otherwise the wilcarding will happen immediately.
I gave this a go and it seemed to fail in the same way

**Comment by dhalbert** [comment]
I was wrong about quotes

**Comment by evaherrada** [comment]
Yeah, so this was due to me copying setup.py from an out of date source and not an issue with release.yml
