### ISSUE TITLE
`set-output` is deprecated in github actions

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/cookiecutter-adafruit-circuitpython#208]
I'm getting this warning for every build/release workflow run:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Looks like changes will need to be made in the cookiecutter's CI worlflows, specifically about normalizing the repo name for `circuitpython-build-tools` arguments.

**Comment by tekktrik** [comment]
Noticed this while working on the new composite actions.  @jepler, as far as resolving the depreciation issue, I can fix it there and I'm hoping to roll out the new CI here and to the libraries this week since I have more time than I thought.

**Comment by tekktrik** [comment]
See also https://github.com/adafruit/workflows-circuitpython-libs/issues/3

**Comment by jepler** [comment]
Yes I was also thinking this would wait until after the transition to the new workflow style

**Comment by tekktrik** [comment]
Looks like we have until June 2023, so I'll try not to go TOO slow! :snail:

**Comment by 2bndy5** [comment]
I already solved this in my own workflows.

There's also a warning about csexton/release-asset-action still using node.js v12.
I have found a more frequently maintained action that can do the same thing, so I don't get the deprecation warnings anymore.

**Comment by dhalbert** [comment]
> I have found a more frequently maintained action that can do the same thing

What did you find?

**Comment by 2bndy5** [comment]
https://github.com/shogo82148/actions-upload-release-asset

It requires the upload URL, but that can be fetched via the context of the github event. Multiple files are supported using a glob pattern(s) as well. See my [release CI for the nRF24L01 lib](https://github.com/nRF24/CircuitPython_nRF24L01/blob/master/.github/workflows/release.yml) I have tested it with my [CircuitPython_Homie lib releases](https://github.com/2bndy5/CircuitPython_Homie/releases/tag/v0.1.4).

**Comment by tekktrik** [comment]
Nice, I can look into this as well, and I'll add it as another item for the new workflow actions.

**Comment by 2bndy5** [comment]
FYI, [the comment in the current cookiecutter workflow](https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/9abfd3d0f29fb28dd62c64caa91ea1e21c119b17/%7B%7B%20cookiecutter.__dirname%20%7D%7D/.github/workflows/release.yml#L49) is outdated and can be entirely removed because actions/upload-release-asset is now archived (not supported anymore).

**Comment by tekktrik** [comment]
Fixed by https://github.com/adafruit/workflows-circuitpython-libs/pull/8
