### ISSUE TITLE
Code of Conduct out of date

### ISSUE THREAD

**Issue by tekktrik** [adafruit/cookiecutter-adafruit-circuitpython#230]
Looks like the CoC should be updated.  I can also handle updating this across the libraries with my tools if we decide to do a text update.

**Comment by kattni** [comment]
@tekktrik I have a WIP update on the CoC at the moment. I'll pick that back up ASAP.  Let's hold on this until that update is in. Thanks!

**Comment by kattni** [comment]
This can be updated at any time. The update did not end up happening.

**Comment by FoamyGuy** [comment]
resolved by #234
