### ISSUE TITLE
Year in copyright notice needs to be updated possibly automatically

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/cookiecutter-adafruit-circuitpython#25]
The copyright notice is currently set to 2017. This could either be updated simply to 2018 or it could become templated with a default year of current year.

**Comment by kevinjwalters** [comment]
I was going to have a look at this to further improve my python skillz

**Comment by tannewt** [comment]
Thanks @kevinjwalters! Templated would be awesome.

**Comment by apatt** [comment]
submitted a pull request for this: https://github.com/adafruit/cookiecutter-adafruit-circuitpython/pull/26

**Comment by kevinjwalters** [comment]
I did get delayed on this but actually had a look yesterday evening and was going to do it today. @apatt perhaps you've already polished this off and are on a roll here?

**Comment by kevinjwalters** [comment]
I can answer my own question: https://stackoverflow.com/questions/30515456/split-string-into-list-in-jinja

I'm not sure why I struggled to find that in docs.

**Comment by apatt** [comment]
@tannewt this is ready to be closed

**Comment by kevinjwalters** [comment]
I agree with previous comment.

I had pondered adding year to the inputs but it's probably a very niche case to change this. If that's true then manual edit post generation creates a less laborious/overwhelming set of questions.

**Comment by kattni** [comment]
Closing. Fixed by #26
