### ISSUE TITLE
Cookiecutter ignoring register and busdevice choices

### ISSUE THREAD

**Issue by kattni** [adafruit/cookiecutter-adafruit-circuitpython#35]
When running `cookiecutter` it asks whether or not the lib depends on `busdevice` and `register`. If you choose no, both are still added to `adafruit_sensorname.py`, `conf.py`, `README.rst`, and `requirements.txt`. The `conf.py` addition may be intentional, but the rest presumably shouldn't have both.

@sommersoft I seem to remember thinking you had noticed this as well.

**Comment by sommersoft** [comment]
I vaguely remember mentioning that I noticed. However, I have since realized that the proper response for `no` is to leave it empty.

We could probably make `n`/`no` an option though.

**Comment by tannewt** [comment]
Ya, this was a cookiecutter-ism. We should check if they added boolean support and add it if not.

**Comment by kattni** [comment]
Looking at it again, the documentation says "leave blank if it does not need it" so this one is apparently on me. I'll remember how to do it moving forward, but it still might not be a bad idea to figure out if it can be updated.

**Comment by sommersoft** [comment]
Still no boolean that I can find in cookiecutter/Jinja2. I do however have 2 suggestions...

1. Use an [`in`](http://jinja.pocoo.org/docs/2.10/templates/#other-operators) on the requirements.txt template, that way only `y` or `yes` will be evaluated to include them:

```
{% if cookiecutter.depends_on_bus_device in ["y", "yes"] -%}
adafruit-circuitpython-busdevice
{%- endif %}
```
----------------------------------------
2. Change bus_device and register to [`Choice Variables`](https://cookiecutter.readthedocs.io/en/latest/advanced/choice_variables.html#choice-variables-1-1) in cookiecutter.json:

```
{
    "library_name": null,
    "depends_on_bus_device": ["No", "Yes"],
    "depends_on_register": ["No", "Yes"],
    "author": null,
    "github_user": "adafruit",
    "library_prefix": "",
    "company": ""
}
```
Which would look like this:
```
Select depends_on_bus_device:
1 - No
2 - Yes
Choose from 1, 2 [1]:
```

**Comment by kattni** [comment]
I think the one that adds the least amount of change to the UI makes the most sense. If we're going to make this change, I would suggest the first one.

**Comment by kattni** [comment]
However, I would want to make sure that leaving it blank still works for everyone who has been doing it correctly all along.

**Comment by sommersoft** [comment]
Agreed. I'll run some iterations tonight.

**Comment by sommersoft** [comment]
I think `in ["y", "yes"]` is the ticket.

![cookie_requirements_test](https://user-images.githubusercontent.com/21211479/47120306-c0866b80-d233-11e8-8b1a-45e44877e08a.png)

![cookie_requirements_test_2](https://user-images.githubusercontent.com/21211479/47120317-c7ad7980-d233-11e8-96e9-8082422a02c9.png)

![cookie_requirements_test_3](https://user-images.githubusercontent.com/21211479/47120325-cd0ac400-d233-11e8-98e1-53bd09dc659d.png)

**Comment by sommersoft** [comment]
Forgot to test an empty response...

![cookie_requirements_test_4](https://user-images.githubusercontent.com/21211479/47120529-aac57600-d234-11e8-8385-c800729bbb89.png)

**Comment by kattni** [comment]
Well done! I like it!

**Comment by sommersoft** [comment]
:tada: 

Now, do we update the documentation to drop "Leave empty if the library won't use BusDevice."? Maybe say explicitly that the answers "y" and "yes" will include, all others will not include? Still working out combinations of words that make sense...

**Comment by kattni** [comment]
We should definitely update the documentation. Continue thinking on how best to word it.

**Comment by sommersoft** [comment]
```
If the library uses BusDevice, enter ``y`` or ``yes`` to include. If the library doesn't use BusDevice, all other entries including empty, will skip this.
```
:thinking:

**Comment by kattni** [comment]
Maybe change `will skip this` to be more explicit. Something like `will not include BusDevice.` or `to skip inclusion of BusDevice.`

**Comment by sommersoft** [comment]
`will not include BusDevice` works good. PR up shortly. (5/5 Hacktober!)
