### ISSUE TITLE
Adding Register even if response is No

### ISSUE THREAD

**Issue by caternuson** [adafruit/cookiecutter-adafruit-circuitpython#38]
Recently ran cookiecutter for a new CP lib. I said "yes" to BusDevice, but "no" to Register. It still put Register in `README.rst`:
```
Dependencies
=============
This driver depends on:

* `Adafruit CircuitPython <https://github.com/adafruit/circuitpython>`_
* `Bus Device <https://github.com/adafruit/Adafruit_CircuitPython_BusDevice>`_
* `Register <https://github.com/adafruit/Adafruit_CircuitPython_Register>`_
```

**Comment by ladyada** [comment]
yeah any response is 'yes' you have to put in a blank line for 'no' - its a little confusing the first time, but i recall scott saying there's no way around it.

**Comment by kattni** [comment]
We added an update that changed that behavior to avoid this confusion: #36 

We need to verify why the fix isn't working now.

**Comment by caternuson** [comment]
Maybe that template logic needs to be included here as well?
https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/master/%7B%7B%20cookiecutter.library_name%20%7D%7D/README.rst#dependencies
```
{%- if cookiecutter.depends_on_bus_device != "" %} * Bus Device {%- endif %} {%- if cookiecutter.depends_on_register != "" %} * Register {%- endif %}
```

**Comment by kattni** [comment]
@sommersoft When you get a chance, can you please take a look at this? Thanks!

**Comment by sommersoft** [comment]
Sorry I totally missed this when I updated `requirements.txt`!!! Fix will be in shortly.
