### ISSUE TITLE
Add a `readme_renderer` check to `build.yml`

### ISSUE THREAD

**Issue by siddacious** [adafruit/cookiecutter-adafruit-circuitpython#61]
I ran into an issue with Adafruit_CircuitPython_ICM20649 :
https://github.com/adafruit/Adafruit_CircuitPython_ICM20649/issues/1
An issue with the parsing of the `README.rst` was preventing it from getting uploaded to PyPi. The symptom was a failing "Release Actions" -> "upload-pypi" job with this error:

![image](https://user-images.githubusercontent.com/1183985/72197264-3d22de00-33d4-11ea-8ba1-701d1530b616.png)

The included URL pointed me to docs that lead me to the 'readme_parser' module that PyPi users. I was able to test with:
```
pip install --user --upgrade setuptools wheel twine readme_renderer
python setup.py sdist
python setup.py bdist_wheel --universal
twine check dist/*
```

**Comment by dherrada** [comment]
Might also need to install testresources, I did when I installed this

**Comment by makermelissa** [comment]
It seems like this step conflicts with the release.yml in that it checks for a file named setup.py to determine if it should upload to PyPI, but without setup.py here it fails build.yml.

**Comment by dherrada** [comment]
@makermelissa oh yeah, I completely overlooked that. I'll make a pr wtih a fix soon.
