### ISSUE TITLE
.travis.yml not generated

### ISSUE THREAD

**Issue by nelsonov** [adafruit/cookiecutter-adafruit-circuitpython#62]
All the documentation says that one of the files to be generated is a config file for Travis CI, however no .travis.yml file is being generated.

`
> ls -al
total 52
drwxr-xr-x 1 lnelson lnelson   278 Feb  8 15:05 .
drwxr-xr-x 1 lnelson lnelson    76 Feb  8 15:05 ..
-rw-r--r-- 1 lnelson lnelson  2148 Feb  8 15:05 circuitpython_clockhand.py
-rw-r--r-- 1 lnelson lnelson  5831 Feb  8 15:05 CODE_OF_CONDUCT.md
drwxr-xr-x 1 lnelson lnelson    84 Feb  8 15:05 docs
drwxr-xr-x 1 lnelson lnelson    74 Feb  8 15:05 examples
drwxr-xr-x 1 lnelson lnelson    18 Feb  8 15:05 .github
-rw-r--r-- 1 lnelson lnelson   102 Feb  8 15:05 .gitignore
-rw-r--r-- 1 lnelson lnelson  1096 Feb  8 15:05 LICENSE
-rw-r--r-- 1 lnelson lnelson 16110 Feb  8 15:05 .pylintrc
-rw-r--r-- 1 lnelson lnelson  2667 Feb  8 15:05 README.rst
-rw-r--r-- 1 lnelson lnelson    59 Feb  8 15:05 .readthedocs.yml
-rw-r--r-- 1 lnelson lnelson    45 Feb  8 15:05 requirements.txt
-rw-r--r-- 1 lnelson lnelson  2013 Feb  8 15:05 setup.py
`

**Comment by ladyada** [comment]
hi we recently moved to github actions, please check the .github folder!

**Comment by nelsonov** [comment]
OK, thank you.
