### ISSUE TITLE
Make Templates Bundle Aware: Adafruit or Community

### ISSUE THREAD

**Issue by sommersoft** [adafruit/cookiecutter-adafruit-circuitpython#73]
In assisting someone with creating a library for the Community Bundle, and providing information in conjunction with the Learn Guide, I realized we could probably do this better.

The Community version will have changes with regards to the CI portion, at minimum. The templated GitHub Actions workflows assume an Adafruit library, and will require changes every time. Further, no option for Travis is provided; which could be desired by the library creator.

Thoughts?

**Comment by Gadgetoid** [comment]
I more or less came here to say this- although I've recently encountered all of these warts and might be better positioned to raise this as a PR if I can find the time.

This CookieCutter is still Adafruit minded with things like the Discord Chat, GitHub Actions and various small bits here and there.

An example: https://github.com/pimoroni/Pimoroni_CircuitPython_LTR559/commit/6de30d84808673c9f488e7796b8c9f8f9d5a8f46

Incidentally I also had a lot of trouble figuring out what to put where during the initial setup. I ended up with "Pimoroni_CircuitPythonPimoroni_CircuitPython_LibraryName" and similar weirdness all over the place:

Here's the mess I managed to make of the docs- https://github.com/pimoroni/Pimoroni_CircuitPython_LTR559/commit/76b31cdbad1749f58fbb288f3de7d171e0571df3

**Comment by siddacious** [comment]
I agree with @Gadgetoid 's input; there are a lot of assumptions in the cookiecutter as is, both about the user's intent and their knowledge. I think there is room to make it easier to use for both Adafruit and Community bundle destined libs.

**Comment by sommersoft** [comment]
@Gadgetoid @siddacious I started working on this a few days ago, and have some skeletal changes working to allow for easier choices. Hope to have something up in a RFC-pull-request soon.

Would love to get any additional thoughts you have on how to make this a little more aware. Probably easier to add notes to that PR, once I get it here.
