### ISSUE TITLE
Make template PyPI status aware

### ISSUE THREAD

**Issue by kattni** [adafruit/cookiecutter-adafruit-circuitpython#74]
Include a prompt to specify whether a library is destined to be deployed to PyPI. If not, add `setup.py.disabled` with a specific string in it, instead of `setup.py`.  

I'm not certain how I feel about adding this due to the fact that whether a library ends up on PyPI may not be a decision made by the author, but that's another issue to address.

**Comment by 2bndy5** [comment]
Just a reminder: pip can install straight from git repos as long as there's a `setup.py` file in the repo root, so deploying to pypi isn't the sole requirement for a valid `setup.py` existence. `requirement.txt` files can also specify a dependency from git repos.
```
python3 -m pip install git+https://github.com/USER_NAME/CircuitPython_LIB_NAME
```
Additionally, one can append the cmd with `@TREE_NAME` to install from a specific branch

**Comment by kattni** [comment]
@2bndy5 This is correct! However, if a library is not destined for PyPI, it means there's no reason to be pip installing it in the first place. This would apply to microcontroller-specific libraries, such as Adafruit CircuitPython CircuitPlayground, or libraries that are basically Python modules, such as Adafruit CircuitPython Logging, where you would want to use the Python version anywhere you would be pip installing. So while it's possible to pip install a repo locally, this feature is meant for libraries that wouldn't work in that case. All libraries that can be used on Linux SBCs etc. end up on PyPI.
