### ISSUE TITLE
Git clone unsuccessful on Windows

### ISSUE THREAD

**Issue by TheGuardianWolf** [adafruit/cookiecutter-adafruit-circuitpython#82]
Quite a straightforward issue with a seemingly complicated fix for cookiecutter v1.7

Windows does not like certain characters in its filenames. These characters appear in files in this repo and prevent cookiecutter from working properly on Windows, this is noted in the README.

To resolve this issue, we need to somehow remove pipes from the filenames. In cookiecutter 2.0, private variables exist such that my fork here will allow clones on a Windows FS: https://github.com/adafruit/cookiecutter-adafruit-circuitpython/compare/master...TheGuardianWolf:master

Unfortunately cookiecutter 2.0 is not released as of yet, Windows users however can use my fork with the latest version of cookiecutter:

```
pip3 install git+git://github.com/cookiecutter/cookiecutter.git
cookiecutter gh:TheGuardianWolf/cookiecutter-adafruit-circuitpython
```

To resolve this issue for the current cookiecutter, I looked into post and pre generation hooks, but these do not allow modifications of the context variables. There seems to be no way to hook into the generation process and modify these variables.

**Comment by dhalbert** [comment]
Thanks for your investigations on this. We can just await 2.0.

The bad character is `|`. Here's a cookiecutter issue on it: https://github.com/cookiecutter/cookiecutter/issues/943.

**Comment by tekktrik** [comment]
@dhalbert this is good now right?

**Comment by tekktrik** [comment]
Unless I'm misunderstanding the issue, or pipes are still an issue.

**Comment by jepler** [comment]
Since #177 we run on Windows and the CI checks it.

**Comment by jepler** [comment]
@TheGuardianWolf I'm sorry I overlooked your branch when making my fix independently of yours!
