### ISSUE TITLE
pylint fails CI on `monotonic_ns` due to old python version in Actions

### ISSUE THREAD

**Issue by siddacious** [adafruit/cookiecutter-adafruit-circuitpython#85]
![pylint_bug](https://user-images.githubusercontent.com/1183985/91923819-1dec0000-ec86-11ea-97ef-828d6f862f80.png)

The above pretty much explains it; `monotonic_ns` exists in both CircuitPython and C Python since 3.7; I'll suggest we start using at least 3.7 if not 3.8 for CI

@kattni @sommersoft @dherrada  please take a look at the above and let me know if I'm missing something

**Comment by siddacious** [comment]
Here's the failure where I first noticed it:
https://github.com/adafruit/Adafruit_CircuitPython_MCP2515/runs/1059350643?check_suite_focus=true

I can still work on the lib for now but this will block me from releasing

**Comment by sommersoft** [comment]
I don't have any objections to bumping the CPython version up. There may be some instances of keyword collisions (`async`, `await` as variable names, etc), but nothing that should be too heavy.

**Comment by siddacious** [comment]
@sommersoft is this (and the other workflow file) the only place that would need an update?
https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/master/%7B%7B%20cookiecutter.library_name%20%7D%7D/.github/workflows/release.yml#L27

**Comment by lesamouraipourpre** [comment]
@dherrada I've noticed you switching libraries to use CPython 3.7 in github actions. Is there a way to auto-close this when you've got through the list?

**Comment by dherrada** [comment]
@lesamouraipourpre maybe... My personal plan is to just go through all the open issues and see which ones are related to pylint failing and close them. Oh, and I already got through the list. I ran it as an Adabot patch which saved me literal days and got them all done in like 15 mins

**Comment by lesamouraipourpre** [comment]
@dherrada I only found this because I has problems with a private repo which was still on CPython 3.6.

Thank you for all the excellent work you do tidying up with these, dare I sare monotonous, tasks.
